### ISSUE TITLE
A few corrections

### ISSUE THREAD

**Issue by lukasbystricky** [chapkachapka/oscar-wilde_poetry#1]
Note that I'm running the tools in development mode, so if nothing happens when you run a tool then you can leave it. 

- [x] Some of the poems have dedications. It's up to you how you want to style those, but lint complains that you're missing CSS for dedications, see here: https://standardebooks.org/manual/1.7.3/single-page#7.3. You can add an ignore for that rule if you think it's appropriate.
- [x] Run semanticate and typogrify
- [x] Run modernize-spelling --no-hyphens, some of those changes should probably be accepted:
  - fulness -> fullness
  - waggons -> wagons
  - phantasies -> fantasies
  - possibly Mahomet -> Muhammad
  - possibly ‘t is -> ‘tis
- [x] Run build-toc, I think you changed a title since you ran it the fist time
- [x] You added the CSS for applying italics to an entire blockquote, so you can remove the line level italics in the epigraphs for "The True Knowledge" and "Lotus Leaves" 
- [x] In content.opf you have the comment: . Is this necessary?

**Comment by chapkachapka** [comment]
Should be all set. A few notes:

1. I think you forgot to paste in the comment you were asking about. If it was this one:
`		
`
I've now removed it--that was left over from when I was trying to add metadata for the original authors of the translated poems.

2. For some reason, even with --no-hyphens modernize-spelling still changed good-night to goodnight; it looks this is getting done in line 140 of spelling.py rather than in the hyphenation dictionary. Is this something I should raise an issue for? It looks like good-night, good-morning, etc. are also affected. Not an issue for this project but I thought I'd ask for a second opinion before raising an issue in tools.

3. I've let build-toc fix one of the two issues it tries to fix; the other one I get is a bug. Not sure if it's fixed in your version yet.

4. I've added styling for these dedications. I didn't use the code you linked to becaue that seems to be intended for a section-level dedication page rather than a p in a header, and I had to target it more specifically to get it to work in all my test readers.

5. Finally, one question. The last poem in the collection is signed "C.3.3." This is Wilde's cell number in Reading Gaol, and was the pseudonym under which this poem was originally published. I haven't given it semantics because it's not a personal name exactly--does it need one?

**Comment by lukasbystricky** [comment]
1. Yes, I did mean that comment. I had actually pasted it in, but markdown marks that as a comment and ignores it. 
2. I'd also noticed that. I filed a PR, but Alex said for good-night, good-morning etc, that since we're replacing a hyphen with a space (instead of connecting two words) that should be handled by modernize_spelling. The case of good-bye to goodbye should be fixed, I can submit another PR for that. 
3. I'm guessing you're objecting to build-toc removing the language tag. Are you sure that's a bug? I'm running the latest version in development mode. 
4. Ok, that seemed to satisfy lint
5. That's a strange case. I'd say you can tag it as an initialism. 

One final thing, lint says to remove the CSS selector for [epub|type~="epigraph"] i .

**Comment by chapkachapka** [comment]
I've made those changes. For #3, the bug is that the Greek language tag from the subtitle was being applied to the title in the TOC, even though the title was in English. It was marked as fixed a day or two ago, but it still gets an unnecessary language tag in my release version.

One last issue: lint now complains about the "initialism" C.3.3., calling it an "initialism with spaces or without periods." I've double checked and there are periods and there aren't spaces, so I'm guessing this is a problem with numbers--it looks like there's a reference to this in a recent lint changelog, so if it works in your version that's probably all it is. Let me know if you think this needs an ignore entry, otherwise it looks clean on my end.

**Comment by lukasbystricky** [comment]
Hmm, I'm getting a similar change when build-toc. In my case it removes the language tag from
`<a href="text/poetry.xhtml#impression-le-réveillon" xml:lang="fr">Impression</a>
` 
I think this is expected behaviour and you should remove that language tag too. 

You can add a lint ignore for the initialism.

**Comment by chapkachapka** [comment]
Interesting; that probably means you have the fixed version; the language tag there came from the subtitle as well, but nobody noticed because "impression" could plausibly be French.

Both of these should now be done.

**Comment by lukasbystricky** [comment]
Yeah, I'm running the development version. Ok, this looks good!
